### ISSUE TITLE
TestHost error

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Testing#188] opened 2015-11-22 14:51 UTC
I having trouble trying get xunit to discover my tests and its showing the following error.
```
------ Discover test started ------
------ Test started: Project: Hashnest.FunctionalTest ------
Starting  Microsoft.Dnx.TestHost [C:\Users\sarin\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-final\bin\dnx.exe --appbase "D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest" Microsoft.Dnx.ApplicationHost --port 35520 Microsoft.Dnx.TestHost --port 53582 --parentProcessId 12452]
Connected to Microsoft.Dnx.TestHost
Discovering tests in 'D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest\project.json'
Error discovering tests in 'D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest\project.json'. 
Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()<---

========== Discover test finished: 0 found (0:00:01.0431483) ==========
```
I using the current `dnvm`, but the other machine work fine.
```
PS C:\Users\sarin> dnvm
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-rc2-15545
```

**Comment by slaneyrw** [comment] 2015-11-23 20:59
I'm getting the same error, but running from the command line works.  Been an issue with Beta8 and RC1.  Are we missing something from VS ?

**Comment by rynowak** [comment] 2015-11-23 22:58
These errors are always the result of mixing incompatible versions of the TestHost, DNX, and xUnit.

Please check the compatibility matrix here to find the right version of xUnit. https://xunit.github.io/docs/getting-started-dnx.html

I'm updating our readme to point to this page, as it will provide more up to date information than we can.

**Comment by slaneyrw** [comment] 2015-11-26 13:03
I can run the tests from the commandline without problems.  I can't get VS2015 test explorer to work.

**Comment by rynowak** [comment] 2015-11-30 06:53
What's your DNX version (`dnvm list`) and xUnit version (`dnu list`)?

**Comment by slaneyrw** [comment] 2015-11-30 22:09
dnvm list

Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
       1.0.0-beta4       clr     x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6       clr     x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6       clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6       coreclr x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6       coreclr x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6-11921 clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6-11921 coreclr x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta6-12254 clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta7       clr     x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta7       clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta7       coreclr x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta7       coreclr x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta8       clr     x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta8       clr     x86          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta8       coreclr x64          C:\Users\slaneyr\.dnx\runtimes
       1.0.0-beta8       coreclr x86          C:\Users\slaneyr\.dnx\runtimes
  *    1.0.0-rc1-final   clr     x86          C:\Users\slaneyr\.dnx\runtimes default

dnu list

  xunit.abstractions 2.0.0-rc3-build2880
  xunit.assert 2.0.0-rc3-build2880
  xunit.execution.AspNet 2.0.0-aspnet-beta5-10305
  xunit.extensibility.core 2.0.0-rc3-build2880
* xunit.runner.aspnet 2.0.0-aspnet-beta6-10480
  xunit.runner.utility.AspNet 2.0.0-aspnet-beta5-10305

**Comment by rynowak** [comment] 2015-12-02 17:26
You should be using `xunit.runner.dnx` not `xunit.runner.aspnet`. https://xunit.github.io/docs/getting-started-dnx.html

The latter is our internal fork that we're maintaining on a temporary basis until the runtime API stabilizes.

**Comment by slaneyrw** [comment] 2015-12-02 21:25
That set was from the latest ASP.NET Identity repo!  I've swapped it across and still get the same error.

    Exception: System.AggregateException: One or more errors occurred. --->     System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
       at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
       at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
    ---> (Inner Exception #0) System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
       at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()<---

dnu list

    * Microsoft.AspNet.Testing 1.0.0-rc2-15962
      xunit.abstractions 2.0.0
      xunit.assert 2.1.0
      xunit.extensibility.core 2.1.0
      xunit.extensibility.execution 2.1.0
      xunit.runner.aspnet 2.0.0-aspnet-rc2-15940
    * xunit.runner.dnx 2.1.0-rc1-build204
      xunit.runner.reporters 2.1.0
      xunit.runner.utility 2.1.0

**Comment by rynowak** [comment] 2015-12-03 01:24
What are you using from `Microsoft.AspNet.Testing`? That library references our private runner and is pulling it in (notice `xunit.runner.aspnet` is showing up in `dnu list` output. 

If you can drop `Microsoft.AspNet.Testing` that should resolve your issue. Notice that it's an `rc2` package, this is why it's going to cause trouble.

**Comment by slaneyrw** [comment] 2015-12-06 20:33
This specific solution is a fork from AspNet/Identity, but I haven't altered any of the project.json files.

They are using ConditionalFactAttribute and FrameworkSkipConditionAttribute in some of their test classes.

Their dependency is specified as `"Microsoft.AspNet.Testing": "1.0.0-*"`, what version should I used instead of a wildcard match to make it work ?

**Comment by rynowak** [comment] 2015-12-07 16:14
I would try using `"Microsoft.AspNet.Testing": "1.0.0-rc1-final"` (if that exists)

**Comment by slaneyrw** [comment] 2015-12-08 21:09
That version can't be found.  So the next question for the folks at Microsoft... are you using VS2015 Test explorer and are the test discovered after build.  Is so, what versions are you using and are they publicly accessible ?

**Comment by rynowak** [comment] 2015-12-08 21:47
You can find this on this feed: http://www.myget.org/F/aspnetmaster/api/v2/

Sorry for the confusion, this isn't a package we normally publish.

The problem is mixing different runtime versions. You cannot mix rc1 versions and rc2 versions and expect things to work gracefully with DNX. `Microsoft.AspNet.Testing 1.0.0-rc2-15962` is pulling in an rc2 build of the TestHost, which is the piece that is integrated with VS.

You can either work with DNX and all your packages fixed on a release (X.0.0-rc1-final) or you can float (X.0.01-*), but you can't mix and match. Working on bleeding edge packages will expose you to a lot more churn and random breaks so I suggest using the release packages if possible.

**Comment by Eilon** [comment] 2016-04-27 21:19
We are not aware of any remaining issues here in the new ASP.NET Core RC2 tooling (not yet available publicly).

**Closed by Eilon** 2016-04-27 21:19 UTC

**Comment by wangkanai** [comment] 2016-05-08 15:30
@Eilon is the ASP.NET Core RC2 tooling available publicly yet?

**Comment by Eilon** [comment] 2016-05-09 06:08
@wangkanai not yet - but we are working on a release for the middle of this month (May).
