### ISSUE TITLE
Tried to run all tests in Hosting and it hung

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Testing#88] opened 2015-04-02 04:56 UTC
```
------ Run test started ------
Starting Microsoft.Framework.TestHost: C:\Users\davifowl\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11447\bin\dnx.exe --appbase "C:\dev\git\ProjectK\Universe\Hosting\test\Microsoft.AspNet.Hosting.Tests" Microsoft.Framework.ApplicationHost --port 5492 Microsoft.Framework.TestHost --port 48391 run --test Microsoft.AspNet.Hosting.HostingEngineTests.HostingEngineThrowsWithNoServer --test Microsoft.AspNet.Hosting.HostingEngineTests.HostingEngineCanBeStarted --test Microsoft.AspNet.Hosting.HostingEngineTests.HostingEngineInjectsHostingEnvironment --test Microsoft.AspNet.Hosting.HostingEngineTests.CanReplaceHostingFactory --test Microsoft.AspNet.Hosting.HostingEngineTests.CanReplaceStartupLoader --test Microsoft.AspNet.Hosting.HostingEngineTests.CanCreateApplicationServicesWithAddedServices --test Microsoft.AspNet.Hosting.HostingEngineTests.EnvDefaultsToDevelopmentIfNoConfig --test Microsoft.AspNet.Hosting.HostingEngineTests.EnvDefaultsToDevelopmentConfigValueIfSpecified --test Microsoft.AspNet.Hosting.HostingEngineTests.WebRootCanBeResolvedFromTheProjectJson --test Microsoft.AspNet.Hosting.HostingEngineTests.IsEnvironment_Extension_Is_Case_Insensitive --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(621093f7a14b4c05fa9845a6f6a24d5cfbe0a3d2) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(b21907cc32cc2e56141b15acaa112e7c5f209b5c) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(a5b05a1a7e3e14f5fba07d6c7503b3416f56bcbf) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(79516603f4e328b1f491bd4047d739afb95daea8) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(c1b2d200eae137649531fcff833772987d091cde) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(028c12289cfb0a9157d8d98fdcde56fa50e43fcf) --test Microsoft.AspNet.Hosting.HostingEngineTests.MapPath_Facts(8516a168ad4c1f39eed84270d9bd86488a8a8b86) --test Microsoft.AspNet.Hosting.Tests.HostingUtilitiesTests.ReadWebRootFromProjectJson --test Microsoft.AspNet.Hosting.Tests.HttpContextFactoryFacts.Mutable_FeatureCollection_Wrapped_For_OwinFeatureCollection --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassMayHaveHostingServicesInjected --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(ae8753da43e5ee3518b76fa7f0e6f5253d2abf29) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(f3c009027fbd58e119e14f70b5afd266e3beb8d8) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(7b6e60ef677507e8df566cd626841b38336f1e11) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(c0d873c89633b7b7d440b619d249ba2a5fed4067) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(ae22137ca7ebdffd0778039f751fd8e8121fceb3) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(ee1eecce287c0519b2afee33cb61fb1931ef9ccd) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(82c6181ef707a09303484b8c787184d00ac91d85) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassAddsConfigureServicesToApplicationServices(be653e50d3084efd64211d467a1a7abf39fc6f42) --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupWithNoConfigureThrows --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassCanHandleConfigureServicesThatReturnsNull --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupClassWithConfigureServicesShouldMakeServiceAvailableInConfigure --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupLoaderCanLoadByType --test Microsoft.AspNet.Hosting.Tests.StartupManagerTests.StartupLoaderCanLoadByTypeWithEnvironment
Running tests in 'C:\dev\git\ProjectK\Universe\Hosting\test\Microsoft.AspNet.Hosting.Tests\project.json'
```

/cc @rynowak @vijayrkn

**Comment by vijayrkn** [comment] 2015-04-02 18:54
This is because VS was doing an indefinite wait. In this case, Test Host is not providing any response. This is fixed in the latest build. VS will wait for 90 seconds max, if we don't get a response, VS will timeout. We need to introduce an 'alive' message on TestHost to indicate TestHost is active.  Also when TestHost fails, VS does not get an ack, Now VS checked every 10 sec to see if connection is alive. If the connection is broken, VS fails.

**Comment by rynowak** [comment] 2015-04-02 19:19
VS waiting with a timeout solves one issue but not the root cause :laughing:

**Comment by shederman** [comment] 2015-05-05 15:29
Any news on this, driving me scatty. No matter what I do I cannot get any tests in the Test Explorer for my project. Tried restarting, killing various processes. Nada. And there seems to be nothing in the way of logging I can find that's useful.

**Comment by matthewDDennis** [comment] 2015-05-08 14:44
I have a similar issue and reported it to https://github.com/xunit/dnx.xunit/issues/29.
Text from my last comment with a repo to demo the issue

I've extracted a minimal project from my code to demo the issue.
 It can be found at https://github.com/matthewDDennis/TestRunnerBugSample.
- you can run tests from a class successfully in VS
- if you attempt to run all test in VS it hangs
- all test run from command line.

**Comment by Eilon** [comment] 2015-07-08 21:11
This should be fixed from https://github.com/aspnet/Testing/issues/109.

**Closed by Eilon** 2015-07-08 21:11 UTC
