### ISSUE TITLE
VS 2015 TestExplorer "Unable to read data from the transport connection" when running Xunit tests

### ISSUE THREAD

**Issue by redknightlois** [aspnet/Testing#200] opened 2016-01-26 21:24 UTC
When trying to execute on Team Explorer I get the following error:

```
------ Run test started ------
------ Test started: Project: Voron.Tests ------
Starting  Microsoft.Dnx.TestHost [C:\Users\Federico\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-update1\bin\dnx.exe --appbase "G:\Src\ravendb-4.0-git\test\Voron.Tests" Microsoft.Dnx.ApplicationHost Microsoft.Dnx.TestHost --port 10531]
Connected to Microsoft.Dnx.TestHost
Running tests in 'G:\Src\ravendb-4.0-git\test\Voron.Tests\project.json'
Error running tests in 'G:\Src\ravendb-4.0-git\test\Voron.Tests\project.json'. 
Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Executor.HostExtensions.ExecuteTests(IHost host, IFrameworkHandle framework, IEnumerable`1 tests)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isRunAllTests)
========== Run test finished: 0 run (0:00:11,6589254) ==========
```

Runs properly when run manually.
Launch settings:
``` 
{
  "profiles": {
    "test": {
      "commandName": "test",
      "sdkVersion": "dnx-coreclr-win-x64.1.0.0-rc1-update1"
    }
  }
}
```

Dependencies: ```"xunit": "2.1.0"``` and ```"xunit.runner.dnx": "2.1.0-rc1-build204"```

Before anyone think otherwise, this error is not related to https://github.com/aspnet/Testing/issues/146 because I am not linking the ```xunit.runner.visualstudio``` assembly.

Also doesnt happen when running with the debugger attached.

**Comment by vijayrkn** [comment] 2016-02-10 19:11
Can you try setting this environment variable and re-run the test - DNX_TESTHOST_TRACE=1 
This should provide more logging info.

**Comment by myarichuk** [comment] 2016-04-15 07:56
Hi,
it seems that I am having similar issue; I've enabled the environmental variable as you suggested and the following is the tracing output:
(Judging by what I saw, a StackOverflowException is the cause of the testing process being terminated)

------ Run test started ------
------ Test started: Project: Voron.Graph.Tests.Dnx ------
Starting  Microsoft.Dnx.TestHost [C:\Users\Admin\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-update2\bin\dnx.exe --appbase "E:\projects\Voron.Graph\tests\Voron.Graph.Tests.Dnx" Microsoft.Dnx.ApplicationHost --port 49658 Microsoft.Dnx.TestHost --port 49678 --parentProcessId 5132]
Connected to Microsoft.Dnx.TestHost
Discovering tests in 'E:\projects\Voron.Graph\tests\Voron.Graph.Tests.Dnx\project.json'

Microsoft.Dnx.TestHost Information: 0 : [ReportingChannel]: Requested Version: 1 - Using Version: 1
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((ProtocolVersion) -> {
  "Version": 1
})
Microsoft.Dnx.TestHost Information: 0 : Starting Discovery
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Initialization_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Initialization_should_work",
  "Id": "e27e502e-1847-07f3-6144-49cfa958f185",
  "LineNumber": 13,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Simple_vertex_read_write_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_vertex_read_write_should_work",
  "Id": "1d8ad0dc-9ce1-4ada-81ad-72753bc3975a",
  "LineNumber": 34,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Simple_vertex_delete_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_vertex_delete_should_work",
  "Id": "934c75c5-abf2-6cfe-601b-12a1e79e4459",
  "LineNumber": 59,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Simple_edge_read_write_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_read_write_should_work",
  "Id": "e9a064d3-123b-375d-9d42-0df8e574de45",
  "LineNumber": 82,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Simple_edge_delete_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_delete_should_work",
  "Id": "b4e095f5-00e8-7ffd-5f5e-beb83b9b4955",
  "LineNumber": 106,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.Simple_edge_read_write_without_data_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_read_write_without_data_should_work",
  "Id": "78195330-b9d5-4822-2cd1-a900aefd4f1b",
  "LineNumber": 142,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\BasicTests.cs",
  "DisplayName": "BasicTests.GetAdjacent_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.GetAdjacent_should_work",
  "Id": "a9c5cb92-3d53-6bbc-9935-4af2d0915c7b",
  "LineNumber": 172,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_without_edges_should_return_first_vertex",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_without_edges_should_return_first_vertex",
  "Id": "cdea255d-8b10-cf4c-264f-ba62df40a717",
  "LineNumber": 14,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_without_limits_should_traverse_all_edges1",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_without_limits_should_traverse_all_edges1",
  "Id": "eed7eff2-6872-dec0-a1f8-73369f23a7cc",
  "LineNumber": 68,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_without_limits_should_traverse_all_edges2",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_without_limits_should_traverse_all_edges2",
  "Id": "8d0313f6-e7b3-7d60-81f2-dc032826e208",
  "LineNumber": 103,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_without_limits_should_traverse_all_edges3",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_without_limits_should_traverse_all_edges3",
  "Id": "fef288b7-f13e-fabb-5c87-7bb85fa9f109",
  "LineNumber": 132,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_with_min_depth_should_traverse_only_relevant_edges1",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_min_depth_should_traverse_only_relevant_edges1",
  "Id": "77e581f6-357c-864b-e4c5-67a8c1d9a92f",
  "LineNumber": 165,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
  "Id": "12da4d27-c55f-6d7c-c67c-e86c9ab71f1b",
  "LineNumber": 219,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_should_travel_loops_once1",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_should_travel_loops_once1",
  "Id": "d357319b-672c-1c6f-96eb-d32bfcc3f65d",
  "LineNumber": 276,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_should_travel_loops_once2",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_should_travel_loops_once2",
  "Id": "340ec23a-3845-270b-e094-983802e4628d",
  "LineNumber": 312,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
  "Id": "d1d9b6e9-9a1b-ddb2-395d-265fd8b7d329",
  "LineNumber": 350,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.TestFound) -> {
  "CodeFilePath": "E:\\projects\\Voron.Graph\\tests\\Voron.Graph.Tests.Dnx\\TraversalTests.cs",
  "DisplayName": "TraversalTests.Traversal_with_max_results_should_return_proper_number_of_results",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_max_results_should_return_proper_number_of_results",
  "Id": "ef6b79ab-32ed-65cd-c4d7-c8603ca151d8",
  "LineNumber": 389,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestDiscovery.Response) -> null)
Microsoft.Dnx.TestHost Information: 0 : Completed Discovery
------ Test started: Project: Voron.Graph.Tests.Dnx ------
Starting  Microsoft.Dnx.TestHost [C:\Users\Admin\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-update2\bin\dnx.exe --appbase "E:\projects\Voron.Graph\tests\Voron.Graph.Tests.Dnx" Microsoft.Dnx.ApplicationHost --port 49658 Microsoft.Dnx.TestHost --port 49681 --parentProcessId 5132]
Connected to Microsoft.Dnx.TestHost
Running tests in 'E:\projects\Voron.Graph\tests\Voron.Graph.Tests.Dnx\project.json'

Microsoft.Dnx.TestHost Information: 0 : [ReportingChannel]: Requested Version: 1 - Using Version: 1
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((ProtocolVersion) -> {
  "Version": 1
})
Microsoft.Dnx.TestHost Information: 0 : Starting Execution
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
  "Id": "d1d9b6e9-9a1b-ddb2-395d-265fd8b7d329",
  "LineNumber": null,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "BasicTests.Simple_edge_read_write_without_data_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_read_write_without_data_should_work",
  "Id": "78195330-b9d5-4822-2cd1-a900aefd4f1b",
  "LineNumber": null,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestResult) -> {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "BasicTests.Simple_edge_read_write_without_data_should_work",
    "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_read_write_without_data_should_work",
    "Id": "78195330-b9d5-4822-2cd1-a900aefd4f1b",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.8720000",
  "StartTime": "2016-04-15T10:50:39.7191594+03:00",
  "EndTime": "2016-04-15T10:50:40.6037898+03:00"
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "BasicTests.GetAdjacent_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.GetAdjacent_should_work",
  "Id": "a9c5cb92-3d53-6bbc-9935-4af2d0915c7b",
  "LineNumber": null,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestResult) -> {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
    "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_max_results_lower_than_actual_results_should_have_no_effect",
    "Id": "d1d9b6e9-9a1b-ddb2-395d-265fd8b7d329",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.8870000",
  "StartTime": "2016-04-15T10:50:39.7131552+03:00",
  "EndTime": "2016-04-15T10:50:40.6167996+03:00"
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
  "Id": "12da4d27-c55f-6d7c-c67c-e86c9ab71f1b",
  "LineNumber": null,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestResult) -> {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "BasicTests.GetAdjacent_should_work",
    "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.GetAdjacent_should_work",
    "Id": "a9c5cb92-3d53-6bbc-9935-4af2d0915c7b",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.0210000",
  "StartTime": "2016-04-15T10:50:40.6167996+03:00",
  "EndTime": "2016-04-15T10:50:40.625806+03:00"
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "BasicTests.Initialization_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Initialization_should_work",
  "Id": "e27e502e-1847-07f3-6144-49cfa958f185",
  "LineNumber": null,
  "Properties": {}
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestResult) -> {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
    "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_min_depth_should_traverse_relevant_edges1_with_DFS",
    "Id": "12da4d27-c55f-6d7c-c67c-e86c9ab71f1b",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.0130000",
  "StartTime": "2016-04-15T10:50:40.6178+03:00",
  "EndTime": "2016-04-15T10:50:40.6278075+03:00"
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "TraversalTests.Traversal_with_max_results_should_return_proper_number_of_results",
  "FullyQualifiedName": "Voron.Graph.Tests.Dnx.TraversalTests.Traversal_with_max_results_should_return_proper_number_of_results",
  "Id": "ef6b79ab-32ed-65cd-c4d7-c8603ca151d8",
  "LineNumber": null,
  "Properties": {}
})

Process is terminated due to StackOverflowException.
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestResult) -> {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "BasicTests.Initialization_should_work",
    "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Initialization_should_work",
    "Id": "e27e502e-1847-07f3-6144-49cfa958f185",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.0440000",
  "StartTime": "2016-04-15T10:50:40.6268071+03:00",
  "EndTime": "2016-04-15T10:50:40.6688364+03:00"
})
Microsoft.Dnx.TestHost Verbose: 0 : [ReportingChannel]: Send((TestExecution.TestStarted) -> {
  "CodeFilePath": null,
  "DisplayName": "BasicTests.Simple_edge_read_write_should_work",
  "FullyQualifiedName": "Voron.Graph.Tests.BasicTests.Simple_edge_read_write_should_work",
  "Id": "e9a064d3-123b-375d-9d42-0df8e574de45",
  "LineNumber": null,
  "Properties": {}
})
Error running tests in 'E:\projects\Voron.Graph\tests\Voron.Graph.Tests.Dnx\project.json'. 
Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Executor.HostExtensions.ExecuteTests(IHost host, IFrameworkHandle framework, IEnumerable`1 tests)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isRunAllTests)
========== Run test finished: 5 run (0:00:07.3299859) ==========

**Comment by myarichuk** [comment] 2016-04-15 08:04
After looking at my code, I replicated this issue. One of my tests was failing due to StackOverflowException. Running just that test would cause the same issue with Dnx Test Host

**Comment by Eilon** [comment] 2016-04-27 21:26
Closing this out because we have made several improvements to the test runner experience in the ASP.NET Core RC2 tooling (not yet available publicly).

@vijayrkn do you think this scenario is now handled better in the VS test runner?

**Closed by Eilon** 2016-04-27 21:26 UTC

**Comment by vijayrkn** [comment] 2016-04-27 21:49
Yes, we have better exception handling and logging in the new tooling. For the above scenario (test throwing a StackOverflowException) you will get an output similar to this.

```
------ Run test started ------
Running tests in 'C:\Users\vramak\Documents\Visual Studio 2015\Projects\ClassLibrary2\src\ClassLibrary2\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Users\vramak\Documents\Visual Studio 2015\Projects\ClassLibrary2\src\ClassLibrary2\project.json" --output "c:\Temp\src\ClassLibrary2\bin\Debug\netstandard1.5" --port 32615 --parentProcessId 15596 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe

Process is terminated due to StackOverflowException.
========== Run test finished: 0 run (0:00:04.0778397) ==========
```

**Comment by Eilon** [comment] 2016-04-28 00:05
Thanks @vijayrkn . Can we update the error message to say that the `Process WAS terminated...`?

**Comment by vijayrkn** [comment] 2016-04-28 00:24
Sure. Will update the error message.

**Comment by Eilon** [comment] 2016-04-28 20:28
Thanks!
