### ISSUE TITLE
TestHost returns the same message (testresult) multiple times for some of the tests.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/Testing#96] opened 2015-04-07 17:15 UTC
TestHost returns the same message multiple times for some of the tests.

Example from MVC solution:

Original Message:

```json
{
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "FullyQualifiedName": "Microsoft.AspNet.Mvc.Core.ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "Id": "0f40f8e2-80d0-30d2-bc26-970a13d6fb90",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.0110000",
  "StartTime": "0001-01-01T00:00:00-08:00",
  "EndTime": "0001-01-01T00:00:00-08:00"
}
Duplicate Message : {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "FullyQualifiedName": "Microsoft.AspNet.Mvc.Core.ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "Id": "0f40f8e2-80d0-30d2-bc26-970a13d6fb90",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00",
  "StartTime": "0001-01-01T00:00:00-08:00",
  "EndTime": "0001-01-01T00:00:00-08:00"
}
Duplicate Message : {
  "Test": {
    "CodeFilePath": null,
    "DisplayName": "ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "FullyQualifiedName": "Microsoft.AspNet.Mvc.Core.ViewDataDictionaryTest.Eval_EvaluatesExpressions",
    "Id": "0f40f8e2-80d0-30d2-bc26-970a13d6fb90",
    "LineNumber": null,
    "Properties": {}
  },
  "Outcome": 1,
  "ErrorMessage": null,
  "ErrorStackTrace": null,
  "DisplayName": null,
  "Messages": [],
  "ComputerName": null,
  "Duration": "00:00:00.0010000",
  "StartTime": "0001-01-01T00:00:00-08:00",
  "EndTime": "0001-01-01T00:00:00-08:00"
}
```

**Comment by rynowak** [comment] 2015-04-07 22:04
This happens what you use `[MemberData(...)]`. It doesn't seem to cause any issues in VS from what I've seen (VS happily displays pass/fail for each case).

https://github.com/aspnet/Mvc/blob/ae4cafc002c8475d116b3c5c0be75fe9deb2cb11/test/Microsoft.AspNet.Mvc.Core.Test/ViewDataDictionaryTest.cs#L439

Is there any real impact to this that you're aware of? Please reopen if so.

**Comment by vijayrkn** [comment] 2015-04-08 17:13
Unit Test framework throws an exception when we try to add the same message (testresult) multiple times.

framework.RecordResult(testResult); 
results in error message - "The specified test case was not found in the current result context"

VS Test output log:
Error displaying test result: ViewDataDictionaryTest.Eval_EvaluatesExpressions. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.Eval_EvaluatesExpressions. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.CopyConstructors_CopyModelMetadata. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.CopyConstructors_CopyModelMetadata. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.CopyConstructors_CopyModelMetadata. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.CopyConstructors_CopyModelMetadata. The specified test case was not found in the current result context.
Error displaying test result: ViewDataDictionaryTest.SetModelDoesNotThrowOnEnumerableModel. The specified test case was not found in the current result context.

**Comment by brentschmaltz** [comment] 2015-04-29 13:25
I think this should be fixed. 
1. It confuses users as it is unexpected and they won't know if they made an error.
2. The Output window is cleared out and displays a line starting with: "Error displaying ..."

**Comment by vijayrkn** [comment] 2015-04-30 23:46
We can repro this with the current csproj and official non aspnet xunit integration

Error message:
Catastrophic failure: System.Runtime.InteropServices.COMException : The specified test case was not found in the current result context.

**Comment by vijayrkn** [comment] 2015-04-30 23:50
![image](https://cloud.githubusercontent.com/assets/3981619/7424657/e8bc54e6-ef58-11e4-8b08-bce095ad284f.png)

Notice VS successfully records 2 testresults for this.

**Comment by Eilon** [comment] 2015-07-08 21:09
This is by design. A test can have multiple results, which is the case of xUnit.net Theory tests that use MemberData.

**Closed by Eilon** 2015-07-08 21:09 UTC
